# YAML anchors need to appear first.
# Keys starting with an underscore are the custom ones, refer to
# https://docs.travis-ci.com/user/build-config-yaml#private-keys-as-yaml-anchors-and-aliases-and-external-tooling

_native_job: &native_job
  script: |
    test/run

language: shell

os: linux

dist: xenial

# This is the default xcode version. The Xcode version defines what
osx_image: xcode9.4

jobs:
  - <<: *native_job
    name: default Ubuntu
    os: linux
  - <<: *native_job
    name: MacOS
    os: osx
 
